# Generated by Django 2.1.7 on 2019-03-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='project',
        ),
    ]
