# Generated by Django 2.1.7 on 2019-03-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_remove_testcase_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '用例管理'},
        ),
    ]
