# Generated by Django 2.1.7 on 2019-03-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20190310_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '用例管理', 'verbose_name_plural': '用例管理'},
        ),
    ]
